name: Keep Render Server Awake

on:
  schedule:
    - cron: '*/10 * * * *' # every 10 minutes
  workflow_dispatch: # allows manual trigger

jobs:
  ping:
    runs-on: ubuntu-latest

    steps:
      - name: Ping Render App
        run: curl -sSf https://backend-ef5a.onrender.com/ping > /dev/null
